import edu.mayo.qdm.executor.drools.PreconditionResult;

import edu.mayo.qdm.patient.*;
import java.util.List;
import edu.mayo.qdm.executor.drools.DroolsUtil
import java.util.Iterator;
import edu.mayo.qdm.executor.drools.*
import java.util.Calendar
import java.util.Arrays;

global DroolsUtil droolsUtil
global SpecificContextManager specificContextManager

rule "Rule 1"
      dialect "mvel"
      no-loop
  when

    $p : Patient( )

    $sc : SpecificContext(id == "1", patient == $p)

    $lab :  Lab(startDate < "12-Jan-2000")  from $p.labs

  then
      System.out.println("1" + $lab);
      modify($sc) { add(new SpecificOccurrence("A", $lab)) }
end

rule "Rule 2"
      dialect "mvel"
      no-loop
  when

    $p : Patient( )

    $sc : SpecificContext(id == "2", patient == $p)

    $lab :  Lab(endDate > "12-Jan-3000")  from $p.labs

  then
      System.out.println("2" + $lab);
      modify($sc) { add(new SpecificOccurrence("A", $lab)) }
end

rule "Rule 3"
      dialect "mvel"
      no-loop
  when

    $p : Patient( )

    $sc : SpecificContext(id == "3", patient == $p)

    $lab :  Lab(concept.code == "c")  from $p.labs

  then
      System.out.println("3" + $lab);
      modify($sc) { add(new SpecificOccurrence("A", $lab)) }
end

rule "Group"
      dialect "mvel"
      no-loop
      //salience -1000

 when

    $p : Patient( )
    $sc : SpecificContext(id == "Group", patient == $p)

    $sc1 : SpecificContext(specificContextTuples.size() > 0, id == "1", patient == $p, $t : specificContextTuples)
    $sc2 : SpecificContext(id == "2", patient == $p, match($t, false))
    $sc3 : SpecificContext(id == "3", patient == $p, match($t, true))

  then
      System.out.println("Group");
      retract($sc)
      insert(specificContextManager.intersect($p, "Group", [$sc1,$sc2,$sc3]))
      //insert(new PreconditionResult("Group", $p))

end

rule "Main"
      dialect "mvel"
      no-loop
      salience -9999
 when

    $p : Patient( )
    $sc1 : SpecificContext(specificContextTuples.size() > 0, id == "Group", patient == $p, $t : specificContextTuples)

  then
      System.out.println("Main");
end

rule "initializeit"
      dialect "mvel"
      no-loop
 when

    $p : Patient( )

  then
      System.out.println("Init");
      insert(new SpecificContext("1", $p));
      insert(new SpecificContext("2", $p));
      insert(new SpecificContext("3", $p));
      insert(new SpecificContext("Group", $p));

end

