import edu.mayo.qdm.executor.drools.PreconditionResult;

import edu.mayo.qdm.patient.*;
import java.util.List;
import edu.mayo.qdm.executor.drools.DroolsUtil
import java.util.Iterator;
import edu.mayo.qdm.executor.drools.*
import java.util.Calendar
import java.util.Arrays;

global DroolsUtil droolsUtil
global SpecificContextManager specificContextManager

rule "Rule 1"
      dialect "mvel"
      no-loop
  when

    $p : Patient( )

    $lab :  Lab(startDate < "12-Jan-2000")  from $p.labs

  then
      System.out.println("1" + $lab);
      insertLogical (new PreconditionResult("1", $p, $lab))
end

rule "Rule 2"
      dialect "mvel"
      no-loop
  when

    $p : Patient( )

    $lab :  Lab(endDate > "12-Jan-3000")  from $p.labs

  then
      System.out.println("2" + $lab);
      insertLogical (new PreconditionResult("2", $p, $lab))

end

rule "Rule 3"
      dialect "mvel"
      no-loop
  when

    $p : Patient( )

    $lab :  Lab(concept.code == "c")  from $p.labs

  then
      System.out.println("3" + $lab);
      insertLogical (new PreconditionResult("3", $p, $lab))

end

rule "Group"
      dialect "mvel"
      no-loop
      //salience -1000

 when

    $p : Patient( )

    PreconditionResult( id == "1", patient == $p)
    PreconditionResult( id == "2", patient == $p)
    //not PreconditionResult( id == "3", patient == $p, event == $event )

  then
      insertLogical (new PreconditionResult("Group", $p))



end

rule "Main"
      dialect "mvel"
      no-loop
      salience -9999
 when

    $p : Patient( )
    PreconditionResult( id == "Group", patient == $p )

    PreconditionResult(id == "so_final", patient == $p)

  then
      System.out.println("Main");
end

rule "so1"
      dialect "mvel"
      no-loop
 when
    $p : Patient( )

        $result : PreconditionResult(id == "1" || id == "ZZZZ", patient == $p )

        PreconditionResult( id == "1", patient == $p, event == $result.event)
        or
        PreconditionResult( id == "ZZZZ", patient == $p, event == $result.event)
  then
   System.out.println("HI");
   insertLogical( new SpecificOccurrenceResult("1", $result.event))

end

rule "so2"
      dialect "mvel"
      no-loop
 when
    $p : Patient( )

        $result : PreconditionResult(id == "2" || id == "ZZZZ", patient == $p )

        PreconditionResult( id == "2", patient == $p, event == $result.event)

        not PreconditionResult( id == "ZZZZ", patient == $p, event == $result.event)
  then
   System.out.println("HI");
   insertLogical( new SpecificOccurrenceResult("2", $result.event))

end

rule "so_final"
      dialect "mvel"
      no-loop
 when
    $p : Patient( )

        SpecificOccurrenceResult( id == "1", $event : event)
        SpecificOccurrenceResult( id == "2", event == $event)
  then
   System.out.println("HI-final");
   insertLogical( new PreconditionResult("so_final", $p))

end
