import edu.mayo.qdm.executor.drools.PreconditionResult;

import edu.mayo.qdm.patient.*;
import java.util.List;
import edu.mayo.qdm.executor.drools.DroolsUtil
import java.util.Iterator;
import edu.mayo.qdm.executor.drools.*
import java.util.Calendar
import java.util.Arrays;

global DroolsUtil droolsUtil
global SpecificContextManager specificContextManager

rule "SO A"
      dialect "mvel"
      no-loop
  when

    $p : Patient( )

    $lab :  Lab(startDate < "12-Jan-2000")  from $p.labs

  then
      System.out.println("1" + $lab);
      insert (new PreconditionResult("SO A", $p, $lab))
end

rule "SO B"
      dialect "mvel"
      no-loop
  when

    $p : Patient( )

    $lab :  Lab(startDate < "12-Jan-2000")  from $p.labs

  then
      System.out.println("1" + $lab);
      insert (new PreconditionResult("SO B", $p, $lab))
end

rule "Rule 3"
      dialect "mvel"
      no-loop
  when

    $p : Patient( )

    $sc : SpecificContext(id == "3", patient == $p)

    $lab :  Lab(concept.code == "c")  from $p.labs

  then
      System.out.println("3" + $lab);
      modify($sc) { add(new SpecificOccurrence("A", "A", $lab)) }
      insert (new PreconditionResult("3", $p, $lab))

end

rule "Group"
      dialect "mvel"
      no-loop
      //salience -1000

 when

    $p : Patient( )
    $sc : SpecificContext(id == "Group", patient == $p)

    PreconditionResult( id == "1", patient == $p )
    PreconditionResult( id == "2", patient == $p )
    not PreconditionResult( id == "3", patient == $p )

    $sc1 : SpecificContext(specificContextTuples.size() > 0, id == "1", patient == $p, $t : specificContextTuples)
    $sc2 : SpecificContext(id == "2", patient == $p, match($t, false))
    $sc3 : SpecificContext(id == "3", patient == $p, match($t, true))

  then
      System.out.println("Group");
      retract($sc)
      insert(specificContextManager.intersect($p, "Group", [$sc1,$sc2,$sc3.negate()]))
      insert (new PreconditionResult("Group", $p))



end

rule "Main"
      dialect "mvel"
      no-loop
      salience -9999
 when

    $p : Patient( )
    PreconditionResult( id == "Group", patient == $p )

  then
      System.out.println("Main");
end

rule "initializeit"
      dialect "mvel"
      no-loop
 when

    $p : Patient( )

  then
      System.out.println("Init");
      insert(new SpecificContext("1", $p));
      insert(new SpecificContext("2", $p));
      insert(new SpecificContext("3", $p));
      insert(new SpecificContext("Group", $p));

end

rule "Occurrence A"
      dialect "mvel"
      no-loop
 when

    $p : Patient( )

    $c : SpecificContext(patient == $p)

    $lab : Lab() from $p.labs

  then
      $c.addToUniverse(new SpecificOccurrence("A", "A", $lab));

end
