import edu.mayo.qdm.executor.drools.PreconditionResult;

import edu.mayo.qdm.patient.*;
import java.util.List;
import edu.mayo.qdm.executor.drools.DroolsUtil
import java.util.Iterator;
import edu.mayo.qdm.executor.drools.SpecificOccurrence
import java.util.Calendar;

global DroolsUtil droolsUtil

rule "insert"
      dialect "mvel"
      no-loop
      salience 99999
  when

    $p : Patient( )

    $lab : DiagnosticStudy (

    ) from $p.labs

  then
      insert( new SpecificOccurrence($lab, "A", "A", $p))
      System.out.println("Inserting...");

end


rule "1"
      dialect "mvel"
      no-loop
  when

    $p : Patient( )

    $so : SpecificOccurrence($event :event, id == "A", patient == $p)

    $lab : Lab ( endDate > "12-Jan-3000", this == $event ) from $p.labs

    not PreconditionResult( event == $lab, id == "1", patient == $p)

  then
      insert( new PreconditionResult("1", $p, $lab))
      //insert( new SpecificOccurrence($lab, "A", "A", $p))
      System.out.println("Rule 1");

end

rule "1'"
      dialect "mvel"
      no-loop
  when

    $p : Patient( )

    $so : SpecificOccurrence($event :event, id == "A", patient == $p)

    not Lab ( endDate > "12-Jan-3000", this == $event ) from $p.labs

  then
      retract($so)
      System.out.println("retract 1");

end

rule "2"
      dialect "mvel"
      no-loop
  when

    $p : Patient( )

    $so : SpecificOccurrence($event :event, id == "A", patient == $p)

    $lab : Lab ( startDate < "12-Jan-2000", this == $event) from $p.labs

    not PreconditionResult( event == $lab, id == "2", patient == $p)

  then
      insert( new PreconditionResult("2", $p, $lab))
      //insert( new SpecificOccurrence($lab, "A", "A", $p))

      System.out.println("Rule 2");

end

rule "2'"
      dialect "mvel"
      no-loop
  when

    $p : Patient( )

    $so : SpecificOccurrence($event :event, id == "A", patient == $p)

    not Lab ( startDate < "12-Jan-2000", this == $event ) from $p.labs

  then
      retract($so)
      System.out.println("retract 2");

end

rule "Master"
      dialect "mvel"
      no-loop
      //salience -999
  when

    $p : Patient( )

    $pr1 : PreconditionResult( id == "1", patient == $p)
    $pr2 : PreconditionResult( id == "2", patient == $p)

  then
      System.out.println("Master: " + $pr1.event + " " + $pr2.event);

end