import edu.mayo.qdm.executor.drools.PreconditionResult;

import edu.mayo.qdm.patient.*;
import java.util.List;
import edu.mayo.qdm.executor.drools.DroolsUtil
import java.util.Iterator;
import edu.mayo.qdm.executor.drools.SpecificOccurrence
import java.util.Calendar;
import edu.mayo.qdm.executor.ResultCallback;
import edu.mayo.qdm.executor.MeasurementPeriod


global DroolsUtil droolsUtil
global ResultCallback resultCallback
global MeasurementPeriod measurementPeriod

declare MeasurementPeriod
    @role( event )
    @timestamp( getStart() )
    @duration( getDuration() )
end

declare Encounter
    @role( event )
    @timestamp( getStartDate() )
    @duration( getDuration() )
end

declare Patient
    @role( event )
    @timestamp( birthdate )
end

rule "rule"
      dialect "mvel"
      no-loop

  when

    $p1 : Patient( )

    Encounter( this during measurementPeriod ) from $p1.encounters


  then
    System.out.println("Here");

end
