import edu.mayo.qdm.executor.drools.PreconditionResult;

import edu.mayo.qdm.patient.*;
import java.util.List;
import edu.mayo.qdm.executor.drools.DroolsUtil
import java.util.Iterator;
import edu.mayo.qdm.executor.drools.SpecificOccurrence
import java.util.Calendar;

global DroolsUtil droolsUtil

rule "2"
      dialect "mvel"
      no-loop
      salience -1
  when

    $p : Patient( birthdate >= "01-Jan-1980")

    $lab : Lab (
        startDate.time + 2 < new java.util.Date("01-Jan-2000").time
    ) from $p.labs

  then
      insert( new PreconditionResult("2", $p, $lab))
      System.out.println("Rule 2");

end

rule "3"
      dialect "mvel"
      no-loop
      salience -1
  when

    $p : Patient( birthdate >= "01-Jan-1980")

    $r : PreconditionResult(id == "2", patient == $p)
    $lab : Lab(
        endDate > "01-Jan-3000",
        this == $r.event
    ) from $p.labs

  then
      insert( new PreconditionResult("3", $p, $lab))
      System.out.println("Rule 3");

end

rule "4"
      dialect "mvel"
      no-loop
      salience -1
  when
    $p : Patient( birthdate >= "01-Jan-1980")

    $r : PreconditionResult(id == "4", patient == $p)

    $lab : Lab(
        this == $r.event,
        startDate < "01-Jan-2000"
    ) from $p.labs

  then
      System.out.println("Rule 4");

end

rule "TEST 1"
      dialect "mvel"
      no-loop
  when
    $p : Patient()

  then
      System.out.println("HERE!!!!!");

end
